# Site settings
title: Savas Labs
email: chris@savaslabs.com
url: http://savaslabs.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: A10564
  secondary: F7D611
  secondary-dark: F6433E

# Footer settings
footer:
  copyright: Savas Labs
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/savas_labs
  - title: bitbucket
    url: https://bitbucket.org/savaslabs
  - title: github
    url: https://github.com/savaslabs

# Postal address (add as many lines as necessary)
address:
  - line: American Underground
  - line: 201 W Main St.
  - line: Durham, NC 27701

# Credits content
credits:
  - <a href="http://jekyllrb.com/">Jekyll</a>

# Build settings
markdown: kramdown
permalink: pretty

# To avoid errors when using Travis-CI
exclude: [vendor]
