# Site settings
title: Savas Labs
email: info@savaslabs.com
url: http://savaslabs.com
description: "Savas Labs, web developers in Durham, North Carolina"

# Color settings (hex-codes without the leading hash-tag)
color:
  light: c8ddf8 # light blue. If you update this, update line 248 of main.css too.
  medium: 9E023B # fuschia
  dark: 14133B # dark blue
  accent: F6433E # orange

# Footer settings
footer:
  copyright: Savas Labs
  location: Location
  social: Around the Web
  contact: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/savas_labs
  - title: bitbucket
    url: https://bitbucket.org/savaslabs
  - title: github
    url: https://github.com/savaslabs

# Postal address (add as many lines as necessary)
address:
  - line: American Underground
  - line: 201 W Main St.
  - line: Durham, NC 27701

# Contact information
contact:
  - line: <a href="mailto:info@savaslabs.com" class="accent-hover">info@savaslabs.com</a>
  - line: (919) 432-4660

# Build settings
markdown: kramdown
permalink: pretty

# To avoid errors when using Travis-CI
exclude: [vendor]

# Blog configuration
paginate: 5
paginate_path: "/blog/page:num/"

# Prose configuration
prose:
  rooturl: '_posts'
  siteurl: 'http://savaslabs.com'
  relativeLinks: 'http://savaslabs.com/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          placeholder: "Choose an Author."
          options:
            - name: "Anne Tomasevich"
              value: "Anne Tomasevich"
            - name: "Chris Russo"
              value: "Chris Russo"
            - name: "Dan Murphy"
              value: "Dan Murphy"
            - name: "Kosta Harlan"
              value: "Kosta Harlan"
            - name: "Tim Stallmann"
              value: "Tim Stallmann"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
