- name: Chris Russo
  firstname: Chris
  title: Founder
  img: chris_square.jpg
  modal-id: 1
  bio: 
  >
    Chris Russo has been a professional web developer since 2007 and made his
    first website on geocities.com when he was 11. He was a big fan of
    <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink"><code>&lt;blink&gt;&lt;/blink&gt;</code></a>
    and was deeply saddened when it became a deprecated element.
    For Savas, Chris most enjoys providing bespoke solutions for clients,
    and writing in the third person. When Chris is not behind the computer,
    he’s probably doing something related to a bicycle. He is the Board President
    of nonprofit hospitality network WarmShowers.org, he serves on the board of his
    local bicycle advocacy organization Bike Durham, he founded a bicycle-powered
    food scraps recycling company called Tilthy Rich Compost, and rode his bicycle
    6,000 miles across the U.S. in the summer of 2008.

- name: Kosta Harlan
  firstname: Kosta
  title: Director of Technology
  img: kosta_square.jpg
  modal-id: 2
  bio:
  >
    Veggies es bonus vobis, proinde vos postulo essum magis kohlrabi welsh onion
    daikon amaranth tatsoi tomatillo melon azuki bean garlic. Gumbo beet greens
    corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts
    fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber
    earthnut pea peanut soko zucchini. Brussels sprout coriander water chestnut
    gourd swiss chard wakame kohlrabi beetroot carrot watercress. Corn amaranth
    salsify bunya nuts nori azuki bean chickweed potato bell pepper artichoke.

- name: Dan Murphy
  firstname: Dan
  title: Developer
  img: dan_square.jpg
  modal-id: 3
  bio:
  >
    Dan has worked as a web developer for the past two years specializing in the Drupal
    platform, developing back-end solutions and implementing responsive front-end designs.
    When he's not nerding-out over the latest advancements in web technology, Dan teaches
    math as an adjunct instructor for Northeastern University. He also loves to spend his
    free time rock climbing, snowboarding, and generally enjoying the great outdoors.
    Prior to web development, Dan worked for a multinational aerospace and defense company
    as a mechanical engineer. He received his B.S. in mechanical engineering from Tufts
    University and his M.B.A. from Babson College.

- name: Tim Stallmann
  firstname: Tim
  title: Developer
  img: tim_square.jpg
  modal-id: 4
  bio:
  >
    Tim Stallmann is a cartographer and web developer. His web development experience dates
    all the way back to the last millennium, back when frames were in fashion. Tim fell
    into Drupal via a web mapping project and has been enjoying exploring the possibilities
    of that framework and building his web skills with the Savas team. Outside of work, Tim
    is an avid <a href="http://cakeyear.tumblr.com">baker</a>, and active in social justice
    work. He's a founding member of the
    <a href="http://www.countercartographies.org">Counter-Cartographies Collective</a>
    and part of the <a href="http://www.ourmaps.net">OurMaps project</a>. He has an MA in
    Mathematics from Duke University, and an MA in Geography from UNC Chapel Hill.

- name: Anne Tomasevich
  firstname: Anne
  title: Developer
  img: anne_square.jpg
  modal-id: 5
  bio:
  >
    Anne Tomasevich received a B.S. in textile engineering and worked at a Contract Research
    Organization for five years before realizing that she actually wants to be a web developer.
    She joins Savas as a fairly new developer with an interest in the front end, particularly
    Sass and CSS3. She just read a book about CSS3 and is inordinately excited about it.
    Besides furiously studying to become a computer geek, Anne enjoys cooking, playing
    old Zelda games, and all things musical. She plays piano (and occasionally ukulele)
    in local bands My Brother, My Sister and Jon Sebastian and the Tresspassers, who
    had a <a href="http://jonsebastian.bandcamp.com/track/nightmare-sisters">song</a>
    featured on NPR Music's Favorite Songs of 2014.
